package com.event.domain;
// Generated 2017-6-11 9:12:32 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * TEvent generated by hbm2java
 */
public class TEvent implements java.io.Serializable,Comparable {

	private Integer eventId;
	private TUser TUserByLeadId;
	private TUser TUserByEventCommitId;
	private TUser TUserByKefuId;
	private String eventTitle;
	private String eventContent;
	private Date eventStarttime;
	private Date eventEndtime;
	private String eventUrl;
	private Integer eventStatus;

	public TEvent() {
	}

	public TEvent(TUser TUserByLeadId, TUser TUserByEventCommitId, TUser TUserByKefuId, String eventTitle,
			String eventContent, Date eventStarttime, String eventUrl, Integer eventStatus, Date eventEndtime) {
		this.TUserByLeadId = TUserByLeadId;
		this.TUserByEventCommitId = TUserByEventCommitId;
		this.TUserByKefuId = TUserByKefuId;
		this.eventTitle = eventTitle;
		this.eventContent = eventContent;
		this.eventStarttime = eventStarttime;
		this.eventUrl = eventUrl;
		this.eventStatus = eventStatus;
		this.eventEndtime=eventEndtime;
	}

	

	public Date getEventEndtime() {
		return eventEndtime;
	}

	public void setEventEndtime(Date eventEndtime) {
		this.eventEndtime = eventEndtime;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public TUser getTUserByLeadId() {
		return this.TUserByLeadId;
	}

	public void setTUserByLeadId(TUser TUserByLeadId) {
		this.TUserByLeadId = TUserByLeadId;
	}

	public TUser getTUserByEventCommitId() {
		return this.TUserByEventCommitId;
	}

	public void setTUserByEventCommitId(TUser TUserByEventCommitId) {
		this.TUserByEventCommitId = TUserByEventCommitId;
	}

	public TUser getTUserByKefuId() {
		return this.TUserByKefuId;
	}

	public void setTUserByKefuId(TUser TUserByKefuId) {
		this.TUserByKefuId = TUserByKefuId;
	}

	public String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(String eventTitle) {
		this.eventTitle = eventTitle;
	}

	public String getEventContent() {
		return this.eventContent;
	}

	public void setEventContent(String eventContent) {
		this.eventContent = eventContent;
	}

	public Date getEventStarttime() {
		return this.eventStarttime;
	}

	public void setEventStarttime(Date eventStarttime) {
		this.eventStarttime = eventStarttime;
	}

	public String getEventUrl() {
		return this.eventUrl;
	}

	public void setEventUrl(String eventUrl) {
		this.eventUrl = eventUrl;
	}

	public Integer getEventStatus() {
		return this.eventStatus;
	}

	public void setEventStatus(Integer eventStatus) {
		this.eventStatus = eventStatus;
	}
	
	

	public int compareTo(String anotherString) {
		return eventContent.compareTo(anotherString);
	}

	@Override
	public int compareTo(Object o) {
		TEvent t=(TEvent) o;
		if(this.eventStarttime.before(t.getEventStarttime())){
			return 1;
		}else{
			return -1;
		}
	}

	
	
	
	
}
