package com.event.domain;

import java.util.Date;

// Generated 2017-6-11 9:12:32 by Hibernate Tools 3.2.2.GA

/**
 * TPlacard generated by hbm2java
 */
public class TPlacard implements java.io.Serializable {

	private Integer placardId;
	private String placardTitle;
	private String placardContent;
	private String placardUrl;
	private String userName;
	private Date placardTime;

	public TPlacard() {
	}

	public TPlacard(String placardTitle, String placardContent, String placardUrl, String userName,Date placardTime) {
		this.placardTitle = placardTitle;
		this.placardContent = placardContent;
		this.placardUrl = placardUrl;
		this.userName = userName;
		this.placardTime=placardTime;
	}

	public Date getPlacardTime() {
		return placardTime;
	}

	public void setPlacardTime(Date placardTime) {
		this.placardTime = placardTime;
	}

	public Integer getPlacardId() {
		return this.placardId;
	}

	public void setPlacardId(Integer placardId) {
		this.placardId = placardId;
	}

	public String getPlacardTitle() {
		return this.placardTitle;
	}

	public void setPlacardTitle(String placardTitle) {
		this.placardTitle = placardTitle;
	}

	public String getPlacardContent() {
		return this.placardContent;
	}

	public void setPlacardContent(String placardContent) {
		this.placardContent = placardContent;
	}

	public String getPlacardUrl() {
		return this.placardUrl;
	}

	public void setPlacardUrl(String placardUrl) {
		this.placardUrl = placardUrl;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	

}
