package com.event.domain;
// Generated 2017-6-11 9:12:32 by Hibernate Tools 3.2.2.GA

/**
 * TPlacard generated by hbm2java
 */
public class TPlacard implements java.io.Serializable {

	private Integer placardId;
	private String placardTitle;
	private String placardContent;
	private String placardUrl;
	private Integer userName;

	public TPlacard() {
	}

	public TPlacard(String placardTitle, String placardContent, String placardUrl, Integer userName) {
		this.placardTitle = placardTitle;
		this.placardContent = placardContent;
		this.placardUrl = placardUrl;
		this.userName = userName;
	}

	public Integer getPlacardId() {
		return this.placardId;
	}

	public void setPlacardId(Integer placardId) {
		this.placardId = placardId;
	}

	public String getPlacardTitle() {
		return this.placardTitle;
	}

	public void setPlacardTitle(String placardTitle) {
		this.placardTitle = placardTitle;
	}

	public String getPlacardContent() {
		return this.placardContent;
	}

	public void setPlacardContent(String placardContent) {
		this.placardContent = placardContent;
	}

	public String getPlacardUrl() {
		return this.placardUrl;
	}

	public void setPlacardUrl(String placardUrl) {
		this.placardUrl = placardUrl;
	}

	public Integer getUserName() {
		return this.userName;
	}

	public void setUserName(Integer userName) {
		this.userName = userName;
	}

}
