package com.event.domain;
// Generated 2017-6-11 9:12:32 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * TRecord generated by hbm2java
 */
public class TRecord implements java.io.Serializable {

	private Integer recordId;
	private TUser TUser;
	private String recordForm;
	private String recordContent;
	private Date recordTime;

	public TRecord() {
	}

	public TRecord(TUser TUser, String recordForm, String recordContent, Date recordTime) {
		this.TUser = TUser;
		this.recordForm = recordForm;
		this.recordContent = recordContent;
		this.recordTime = recordTime;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getRecordForm() {
		return this.recordForm;
	}

	public void setRecordForm(String recordForm) {
		this.recordForm = recordForm;
	}

	public String getRecordContent() {
		return this.recordContent;
	}

	public void setRecordContent(String recordContent) {
		this.recordContent = recordContent;
	}

	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

}
