package com.event.domain;
// Generated 2017-6-11 9:12:32 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TTalk generated by hbm2java
 */
public class TTalk implements java.io.Serializable {

	private Integer talkId;
	private TUser TUserByKefuId;
	private Integer eventId;
	private TUser TUserByKehuId;
	private Set records = new HashSet(0);

	public TTalk() {
	}

	public TTalk(TUser TUserByKefuId, TUser TUserByKehuId,Set records,Integer eventId) {
		this.TUserByKefuId = TUserByKefuId;
		this.TUserByKehuId = TUserByKehuId;
		this.eventId=eventId;
		this.records=records;
	}

	public Integer getTalkId() {
		return this.talkId;
	}

	public void setTalkId(Integer talkId) {
		this.talkId = talkId;
	}

	
	public Integer getEventId() {
		return eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public TUser getTUserByKefuId() {
		return this.TUserByKefuId;
	}

	public void setTUserByKefuId(TUser TUserByKefuId) {
		this.TUserByKefuId = TUserByKefuId;
	}

	public TUser getTUserByKehuId() {
		return this.TUserByKehuId;
	}

	public void setTUserByKehuId(TUser TUserByKehuId) {
		this.TUserByKehuId = TUserByKehuId;
	}

	public Set getRecords() {
		return records;
	}

	public void setRecords(Set records) {
		this.records = records;
	}

	
}
